- name: sudo su
  shell: sudo su

- name: install perl module
  yum:
    name: perl-Module-Install.noarch

- name: install python module
  yum:
    name: MySQL-python,libselinux-python

- name: install some dependencies
  yum:
    name: wget,numactl
    
- name: query exsits package or libs(centos 7)
  shell: rpm -qa|grep mariadb
  register: mariadbPk
  ignore_errors: True
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  
- name: remove mariadb libs 
  shell: rpm -e --nodeps {{item}}
  with_items: "{{mariadbPk.stdout_lines | default([])}}"
  when:
    - item != ""
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  
- name: query exsits package or libs(centos 6)
  shell: rpm -qa|grep mysql-libs-5.1
  register: mysqlPk
  ignore_errors: True
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
  
- name: remove mysql-5.1 libs 
  shell: rpm -e --nodeps {{item}}
  with_items: "{{mysqlPk.stdout_lines | default([])}}"
  when:
    - item != ""
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: init package dir
  file:
    path: "{{mysql_package_dir}}"
    state: directory
    mode: 0755