---
- name: install mysql 5.6
  hosts: mysql
  
  roles:
    - 
      role: prepare_mysql_env
    - 
      role: install_mysql_server_5.6
    - 
      role: install_mysql_devel_5.6
    - 
      role: install_mysql_client_5.6
    - 
      role: config_mysql