---
- name: war server restart
  hosts: war_server
  remote_user: "{{remote_user}}"

  roles:
  - 
    role: check_port_use_and_kill
    server_config: "{{bs_config}}"
  - 
    role: start_server
    server_config: "{{bs_config}}"
  - 
    role: wait_port
    server_config: "{{bs_config}}"