---
- name: center server restart
  hosts: center_server
  remote_user: "{{remote_user}}"

  roles:
  - 
    role: check_center_port_use_and_kill
    server_config: "{{center_config}}"
  - 
    role: start_center_server
    server_config: "{{center_config}}"
  - 
    role: wait_center_port
    server_config: "{{center_config}}"