---
#- include: sync_date.yml

- name: war server start
  hosts: war_server
  remote_user: "{{remote_user}}"

  roles:
  - 
    role: check_port_stop
    server_config: "{{bs_config}}"
  - 
    role: init_directory
    server_config: "{{bs_config}}"
  - 
    role: copy_and_extract
    server_config: "{{bs_config}}"
  - 
    role: template_war_config
    server_config: "{{bs_config}}"
  - 
    role: start_server
    server_config: "{{bs_config}}"
  - 
    role: wait_port
    server_config: "{{bs_config}}"

