---
- name: center server update without start
  hosts: center_server
  remote_user: "{{remote_user}}"

  roles:
  - 
    role: check_center_port_use_and_kill
    server_config: "{{center_config}}"
  - 
    role: init_center_directory
    server_config: "{{center_config}}"
  - 
    role: copy_and_extract_center
    server_config: "{{center_config}}"
  - 
    role: template_center_config
    server_config: "{{center_config}}"