- name: add need database
  mysql_db:
    name: "{{item.db_name_pre}}"
    state: present
    encoding: "utf8"
    login_user: "{{item.db_user}}"
    login_password: "{{item.db_pwd}}"
    login_host: "{{item.db_host}}"
    login_port: "{{item.db_port | default(3306)}}"
    config_file: /etc/my.cnf
  with_items: "{{server_config | default([])}}"
  when: 
    - allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"
  
- name: import DDL
  mysql_db:
    name: "{{item.db_name_pre}}"
    state: import
    # target: "{{create_db_sql_file}}"
    target: "{{item.path}}/data/sql/create_game.sql"
    login_user: "{{item.db_user}}"
    login_password: "{{item.db_pwd}}"
    login_host: "{{item.db_host}}"
    login_port: "{{item.db_port | default(3306)}}"
    config_file: /etc/my.cnf
  with_items: "{{server_config | default([])}}"
  when: 
    - allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"