- name: check if server is running
  shell: ps ax|grep {{item.path}}/|grep -v grep|awk '{print $1}'
  with_items: "{{server_config | default([])}}"
  ignore_errors: True
  register: psResult
  when: 
    - "allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)"
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"

- name: kill running process
  shell: kill -15 {{item.stdout}}
  when: item|changed and item.stdout != ""
  with_items: "{{psResult.results | default([])}}"
  
- name: wait server stop if not
  wait_for:
    port: "{{item.port}}"
    timeout: 30
    state: stopped
  with_items: "{{server_config | default([])}}"
  when: 
    - "allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)"
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"