- name: mode 755 start.sh file
  file:
    path: "{{item.path}}/start.sh"
    state: file
    mode: 0755
  with_items: "{{server_config | default([])}}"
  when: 
    - "allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)"
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"

- name: mode 755 stop.sh file
  file:
    path: "{{item.path}}/stop.sh"
    state: file
    mode: 0755
  with_items: "{{server_config | default([])}}"
  when: 
    - "allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)"
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"
    
- name: stop server
  shell: sh stop.sh
  args:
    chdir: "{{item.path}}"
  with_items: "{{server_config | default([])}}"
  when: 
    - "allow_ports is undefined or {{[item.port]}} | issubset(allow_ports)"
    - "allow_gc_ids is undefined or {{[item.gc_id]}} | issubset(allow_gc_ids)"