- name: add php to PATH
  blockinfile:
    block: |
      export PATH=$PATH:{{php_install_dir}}/bin
    marker: "# {mark} php path"
    dest: /etc/profile

- name: source /etc/profile
  shell: source /etc/profile
  
- name: install php alternatives
  shell: update-alternatives --install /usr/bin/php php {{php_install_dir}}/bin/php 56000
  
- name: correct php version selected
  alternatives: name=php path={{php_install_dir}}/bin/php

- name: alternatives link created
  alternatives: name=php link=/usr/bin/php path={{php_install_dir}}/bin/php